### ISSUE TITLE
Live preview in a iframe

### ISSUE THREAD

**Issue by kevinsimper** [juanpabloaj/platon#5]
I think there should be a way to have livepreview in a iframe next to, this will make it a awesome quick markdown presentation tool, just like jsbin/jsfiddle is for quick prototypes.

**Comment by juanpabloaj** [comment]
Is a great idea @kevinsimper , but what is the best option? one iframe with one slide preview or a slide list ?

![iframe vs slide list](http://f.cl.ly/items/103Q1S1F2n3I2d0w323X/Platon_io.png)

**Comment by kevinsimper** [comment]
That looks awesome! :dancers:  That would be so awesome! It will be like creating a slideshow in Keynote or Google Slides but not actually be a fucking nightmare! :smile:

**Comment by juanpabloaj** [comment]
ok, now have the iframe, thanks @kevinsimper

**Comment by kevinsimper** [comment]
It needs to be full height :P and you should trigger print mode so it is just a long list instead of showing one slide a time

**Comment by juanpabloaj** [comment]
how I can activate the print mode in a iframe ?

**Comment by kevinsimper** [comment]
I see know, other libraries has a way to trigger print layout in the url like `?preview`, so Remark would have to be modified a little bit, but the print code is here https://github.com/gnab/remark/blob/e220ee1b4278819b0cb8be02c5cc7cbc7e8f8638/src/remark/components/printing/printing.js
